// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa-o4jXgu6PIGrv3z7RJYXyaMOGAJNCcc',
    appId: '1:408620401329:web:04d2093f896173a3329890',
    messagingSenderId: '408620401329',
    projectId: 'flutter-auth-7d525',
    authDomain: 'flutter-auth-7d525.firebaseapp.com',
    storageBucket: 'flutter-auth-7d525.appspot.com',
    measurementId: 'G-S6169MZXKT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvOHTggla1pwgVjuen4zzh9Ms-dtxrpt0',
    appId: '1:408620401329:android:8ad195fbfefb723f329890',
    messagingSenderId: '408620401329',
    projectId: 'flutter-auth-7d525',
    storageBucket: 'flutter-auth-7d525.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARvIgnKAgcCpHCnV0xryBF8qTU3_a1hsk',
    appId: '1:408620401329:ios:6c7fa2e794725043329890',
    messagingSenderId: '408620401329',
    projectId: 'flutter-auth-7d525',
    storageBucket: 'flutter-auth-7d525.appspot.com',
    iosClientId: '408620401329-turvp8006uuvvt07d6v58nkkes8k9uet.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARvIgnKAgcCpHCnV0xryBF8qTU3_a1hsk',
    appId: '1:408620401329:ios:05ce06563b8f693d329890',
    messagingSenderId: '408620401329',
    projectId: 'flutter-auth-7d525',
    storageBucket: 'flutter-auth-7d525.appspot.com',
    iosClientId: '408620401329-df912dpfeupofu66taltorgfq5k54gkb.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuth.RunnerTests',
  );
}
